[package]
name = "gscc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
derive_more = {version = "1.0.0-beta.6", features = ["from", "display"]}
ignore = "0.4.22"
